rule samtools_view:
    input:
        "{sample}.sam"
    output:
        "{sample}.bam",
	idx="{sample}.bai"
    log:
        "{sample}.log"
    params:
        extra="" # optional params string
    threads: 2
    wrapper:
        "master/bio/samtools/view"
