name: MMseqs2 workflows
url: https://github.com/soedinglab/mmseqs2
description: |
  ultra fast and sensitive sequence search and clustering suite
authors:
  - Filipe G. Vieira
input:
  - input file(s)
output:
  - output file(s)
params:
  - extra: additional program arguments
notes: |
  * Keys for `input` and `output` files need to match `vsearch` arguments, (e.g. input) `uchime_denovo`, `cluster_fast`, `fastx_uniques`, `maskfasta`, `fastq_convert`, `fastq_mergepairs`, or (e.g. output) `chimeras`, `fastaout`, `fastqout`, `output`.
